In [1]:
import pandas as pd
import numpy as np
from keras import layers
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_excel('nilai_rapot.xlsx')

In [ ]:
X=data.iloc[:,0:5].values    # Mengambil data kolom variabel input 
y=data.iloc[:,-1].values     # Mengambil data kolom variabel output
y = to_categorical(y)
print(X)
print(y)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
sc = scaler.transform(X)
sc

In [5]:
from sklearn.model_selection import train_test_split   # Membagi data training dan data testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [6]:
# Membuat model neural network menggunakan Keras
model = Sequential()

# Menambahkan lapisan input dengan 5 unit dan fungsi aktivasi relu
model.add(Dense(units=5, input_dim=5, activation="sigmoid"))

# Menambahkan lapisan hidden dengan 8 unit dan fungsi aktivasi relu
model.add(Dense(units=8, activation="sigmoid"))

# Menambahkan lapisan hidden dengan 6 unit dan fungsi aktivasi relu
model.add(Dense(units=6, activation="sigmoid"))

# Menambahkan lapisan output dengan 3 unit dan fungsi aktivasi softmax
model.add(Dense(units=3, activation="softmax"))

In [7]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
model.fit(X_train, y_train, epochs=200, batch_size=10)

In [9]:
# Melakukan prediksi
y_pred = model.predict(X_test)

1/1 [==============================] - 1s 1s/step


In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [11]:
# Membuat confusion matrix
confusion_mat = confusion_matrix(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1))

# Menghitung nilai accuracy, precision, recall, dan f-measure
accuracy = accuracy_score(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1))
precision = precision_score(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1), average="micro")
recall = recall_score(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1), average="micro")
f_measure = f1_score(np.argmax(y_test, axis=1), np.argmax(y_pred, axis=1), average="micro")

# Menampilkan hasil
print("Confusion matrix:")
print(confusion_mat)
print("Accuracy  : {:.2f}%".format(accuracy*100))
print("Precision : {:.2f}%".format(precision*100))
print("Recall    : {:.2f}%".format(recall*100))
print("F-measure : {:.2f}%".format(f_measure*100))


Confusion matrix:
[[16  0  0]
 [ 3  0  0]
 [ 2  0  0]]
Accuracy  : 76.19%
Precision : 76.19%
Recall    : 76.19%
F-measure : 76.19%


In [12]:
input_data = (40.5, 90, 90.3, 90, 98)
input_data_as_numpy_array = np.array(input_data)
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)
std_data = scaler.transform(input_data_reshape)
print(std_data)
prediction = model.predict(std_data)
print(prediction)

prediction_class = np.argmax(prediction, axis=1)

if prediction_class == 0:
    print("Anda Masuk Jurusan Keperawatan")
elif prediction_class == 1:
    print("Anda Masuk Jurusan Farmasi")
else:
    print("Anda Masuk Jurusan TLM")



[[-8.50242822  1.33317272  1.70384009  1.28129496  3.37069002]]
1/1 [==============================] - 1s 615ms/step
[[0.62096727 0.20409809 0.17493469]]
Anda Masuk Jurusan Keperawatan


In [13]:
import pickle

In [14]:
filename = 'ann_model_clasifier.sav'
pickle.dump(model, open(filename, 'wb'))

Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers\dense
......vars
.........0
.........1
...layers\dense_1
......vars
.........0
.........1
...layers\dense_2
......vars
.........0
.........1
...layers\dense_3
......vars
.........0
.........1
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........13
.........14
.........15
.........16
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
Keras model archive saving:
File Name                                             Modified             Size
config.json                                    2023-01-06 22:37:17         2256
metadata.json                                  2023-01-06 22:37:17           64
variables.h5                                   2023-01-06 22:37:18        27144
